### PR TITLE
Calculating baseurl length instead of assumig based on default settings

### LINKED ISSUE #10: Wrong id for short ids
```
"http://localhost:8983/fedora/rest/test/te/st/5/test5/files"
(byebug) p ActiveFedora::Base.uri_to_id(uri)
"files"
```
I would expect `test5/files` instead

getting the wrong id for short ids.

### PR DESCRIPTION
**Pull request by escowles**
* adding tests for templates of varying lengths
* Fixes #10

### CODE REVIEW

**Comment by escowles** [comment]
Hmm, the Travis build is failing because of this:

https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora.rb#L210

@jcoyne, do I need to set the environment in the Rakefile?

**Comment by jcoyne** [comment]
@escowles that error is saying that RAILS_ENV is set. But I don't see anywhere in the code that sets that, so I'm confused.

**Comment by escowles** [comment]
It seems strange that Travis would set that without us configuring it.  The other way to handle this would be to explicitly set the 'environment' variable.  I tried to add that to the Rakefile but nothing worked for me.

**Comment by escowles** [comment]
I resolved the Travis issue by explicitly specifying the rake invocation with the environment variable, and stubbing out the AF config to prevent attempts to connect to Fedora.

**Pull request merged**
